### ISSUE TITLE
FSE Application - NOV Report - Reorder Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#64]
Please move the COMMENTS column before VIOLATION TYPE.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Comments field is missing from the report altogether.  Note that Compliance Comments and Comments are two separate fields.

**Comment by kanglu666** [comment]
"Please move the COMMENTS column before VIOLATION TYPE."
this is done; 
and "Compliance Comments" is still in the report after the "enforcement action" field

**Comment by JMurk** [comment]
![image](https://cloud.githubusercontent.com/assets/5805454/4448230/4ad24eb4-4811-11e4-8116-2e9240d2f267.png)

"Comments" is still not in the report.

**Comment by kanglu666** [comment]
"Comments" column has been added in NOV report. ready for test

**Comment by JMurk** [comment]
Confirmed complete.
